#include "motors.h"

#include <stdio.h>

#include <avr/interrupt.h>

#include "fault.h"

void init_motors(void)
{
    // X Motor Pins
    INIT_OUTPUT_PIN(X_MOTOR_ENABLE,    X_MOTOR_DISABLED);
    INIT_OUTPUT_PIN(X_MOTOR_DIRECTION, X_MOTOR_DIRECTION_POSITIVE);
    INIT_OUTPUT_PIN(X_MOTOR_STEP,      X_MOTOR_STEP_OFF);

    // Y Motor Pins
    INIT_OUTPUT_PIN(Y_MOTOR_ENABLE,    Y_MOTOR_DISABLED);
    INIT_OUTPUT_PIN(Y_MOTOR_DIRECTION, Y_MOTOR_DIRECTION_POSITIVE);
    INIT_OUTPUT_PIN(Y_MOTOR_STEP,      Y_MOTOR_STEP_OFF);

    // Z Motor Pins
    INIT_OUTPUT_PIN(Z_MOTOR_ENABLE,    Z_MOTOR_DISABLED);
    INIT_OUTPUT_PIN(Z_MOTOR_DIRECTION, Z_MOTOR_DIRECTION_POSITIVE);
    INIT_OUTPUT_PIN(Z_MOTOR_STEP,      Z_MOTOR_STEP_OFF);
}

ISR(X_WATCHDOG_TIMER_COMP_vect)
{
    trigger_fault(F_SI);
}

ISR(Y_WATCHDOG_TIMER_COMP_vect)
{
    trigger_fault(F_SI);
}

ISR(Z_WATCHDOG_TIMER_COMP_vect)
{
    trigger_fault(F_SI);
}
