#!/usr/bin/python

# Slow pulsed dwell.

import sched_test

input = """dt=280000
lm=t
lp=600
pi=70000
pl=6000
re=n
rf=n
rv=y
R
Qd
W
"""

expected = """Kerfburn Back End, built [...]
Ready
V aa=0 dt=280000 ia=n il=0 lm=t lp=600 ls=m m0=0 ma=+0 oc=n oo=n pd=0 pi=70000 pl=6000 re=n rf=n ri=0 rl=n rm=n rp=n rq=n rr=n rs=n rv=y rw=n xd=+0 yd=+0 zd=+0
enqueue_atom_X: a = A_DISABLE_STEP
enqueue_atom_Y: a = A_DISABLE_STEP
enqueue_atom_Z: a = A_DISABLE_STEP
enqueue_atom_P: a = A_SET_MAIN_POWER_LEVEL
enqueue_atom_P: a = 600
enqueue_atom_P: a = A_SET_MAIN_PULSE_DURATION
enqueue_atom_P: a = 6000
enqueue_atom_P: a = A_SET_VISIBLE_LASER_OFF
enqueue_atom_P: a = A_SET_MAIN_LASER_OFF
enqueue_atom_P: a = 64512
enqueue_atom_X: a = 64512
enqueue_atom_Y: a = 64512
enqueue_atom_Z: a = 64512
maybe_start_engine
enqueue_atom_P: a = A_SET_MAIN_LASER_PULSED
enqueue_atom_P: a = 5488
enqueue_atom_X: a = 64512
enqueue_atom_Y: a = 64512
enqueue_atom_Z: a = 64512
maybe_start_engine
enqueue_atom_P: a = A_SET_MAIN_LASER_OFF
enqueue_atom_P: a = 64512
enqueue_atom_P: a = A_SET_MAIN_LASER_PULSED
enqueue_atom_P: a = 5488
enqueue_atom_X: a = 64512
enqueue_atom_Y: a = 64512
enqueue_atom_Z: a = 64512
maybe_start_engine
enqueue_atom_P: a = A_SET_MAIN_LASER_OFF
enqueue_atom_P: a = 64512
enqueue_atom_P: a = A_SET_MAIN_LASER_PULSED
enqueue_atom_P: a = 5488
enqueue_atom_X: a = 64512
enqueue_atom_Y: a = 64512
enqueue_atom_Z: a = 64512
maybe_start_engine
enqueue_atom_P: a = A_SET_MAIN_LASER_OFF
enqueue_atom_P: a = 64512
enqueue_atom_P: a = A_SET_MAIN_LASER_PULSED
enqueue_atom_P: a = 5488
enqueue_atom_X: a = 21952
enqueue_atom_Y: a = 21952
enqueue_atom_Z: a = 21952
maybe_start_engine
start_engine
await_engine_stopped
"""

sched_test.test(input, expected)
