#!/usr/bin/python

# Move +X and +Y, constant speed, positive direction, fast.

import sched_test

input = """aa=1
m0=1000
ma=+0
xd=+5
yd=+3
re=n
rf=n
rv=y
R
Qm
W
"""

expected = """Kerfburn Back End, built [...]
Ready
V aa=1 dt=0 ia=n il=0 lm=o lp=0 ls=m m0=1000 ma=+0 oc=n oo=n pd=0 pi=0 pl=0 re=n rf=n ri=0 rl=n rm=n rp=n rq=n rr=n rs=n rv=y rw=n xd=+5 yd=+3 zd=+0
enqueue_atom_P: a = A_SET_MAIN_LASER_OFF
enqueue_atom_P: a = A_SET_VISIBLE_LASER_OFF
enqueue_atom_X: a = A_ENABLE_STEP
enqueue_atom_X: a = 16000
enqueue_atom_Y: a = A_ENABLE_STEP
enqueue_atom_Y: a = 26666
maybe_start_engine
enqueue_atom_X: a = 16000
enqueue_atom_Y: a = 26667
maybe_start_engine
enqueue_atom_X: a = 16000
enqueue_atom_Y: a = 26667
maybe_start_engine
enqueue_atom_X: a = 16000
maybe_start_engine
enqueue_atom_X: a = 16000
maybe_start_engine
start_engine
await_engine_stopped
"""

sched_test.test(input, expected)
